name: Formatting python code
on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'
jobs:
  autoyapf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use autoyapf
        uses: mritunjaysharma394/autoyapf@v1.0.2-beta
        with:
          args: --style pep8 --recursive --in-place **/*.py .