name: Formatting python code
on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'
jobs:
  autoyapf:
    runs-on: ubuntu-latest
    steps:
      - name: Use autoyapf
        uses: mritunjaysharma394/autoyapf@v1.0.2
        with:
          args: --style pep8  .